name: Rotate Profile Quote

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    update-quote:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: Rotate quote
              run: python rotate_quote.py

            - name: Commit and push changes
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add README.md
                git diff --quiet && exit 0
                git commit -m "auto-rotate profile quote"
                git push https://x-access-token:${{ secrets.GH_PAT_NAME_README }}@github.com/PromisedRain/PromisedRain.git HEAD:main
